[package]
name = "sdtimer"
version = "0.1.0"
authors = ["Emil Ernerfeldt <emil.ernerfeldt@gmail.com>"]
license = "MIT OR Apache-2.0"
edition = "2021"
rust-version = "1.65"
publish = false


[dependencies]
eframe = "0.21.2"
tracing-subscriber = "0.3"
rodio = "0.17.1"